version: '3.8'

services:
    postgres:
        container_name: postgres
        image: postgres:12.2-alpine
        ports:
            - 5432:5432
        volumes:
            - data:/data/db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
volumes:
    data:
